import {
  LayoutDashboard,
  Settings,
  Bell,
  X,
  Menu,
  Sun,
  Moon,
  Download,
  Upload,
  Search,
  ChevronDown,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  ArrowBigUp,
  ArrowBigDown,
  ArrowRight,
  TrendingUp,
  TrendingDown,
  Minus,
  Plus,
  Info,
  AlertCircle,
  AlertTriangle,
  CheckCircle,
  XCircle,
  BarChart3,
  LineChart,
  PieChart,
  Activity,
  Sparkles,
  Lightbulb,
  Save,
  Trash2,
  Edit,
  Copy,
  ExternalLink,
  Wifi,
  CloudOff,
  Cloud,
  Calendar,
  CalendarDays,
  Clock,
  Users,
  User,
  CreditCard,
  DollarSign,
  Wallet,
  ShoppingCart,
  ShoppingBag,
  Store,
  Package,
  Boxes,
  Warehouse,
  Factory,
  FlaskConical,
  Scale,
  Gauge,
  Target,
  Award,
  Trophy,
  Flag,
  Zap,
  ArrowLeftRight,
  ArrowUpDown,
  GitCompare,
  Layers,
  Grid3X3,
  FileText,
  Printer,
  Mail,
  MessageCircle,
  Phone,
  Monitor,
  Bot,
  Truck,
  Merge,
  SlidersHorizontal,
  Repeat,
  ListChecks,
  ClipboardCheck,
  Droplets,
  Leaf,
  type LucideIcon,
  RefreshCw,
  Heart,
  CircleDot,
  MoreHorizontal,
  Expand,
  Shrink,
  RotateCw,
  Table,
  Eye,
  Filter,
  Percent,
  Hash,
  TreeDeciduous,
  ArrowUp,
  ArrowDown,
  ShieldCheck,
  UtensilsCrossed,
  Star,
  Plug,
  Database,
  IdCard,
  BellRing,
  ArrowDownUp,
} from 'lucide-react';

/**
 * Material Icon name → Lucide component mapping
 * Used by DynamicIcon to bridge string-based icon references
 */
export const ICON_MAP: Record<string, LucideIcon> = {
  // Navigation & UI
  dashboard: LayoutDashboard,
  menu: Menu,
  close: X,
  settings: Settings,
  notifications: Bell,
  search: Search,
  expand_more: ChevronDown,
  expand_less: ChevronUp,
  chevron_left: ChevronLeft,
  chevron_right: ChevronRight,
  open_in_new: ExternalLink,
  grid_view: Grid3X3,
  filter_list: Filter,

  // Actions
  download: Download,
  upload: Upload,
  save: Save,
  delete: Trash2,
  delete_outline: Trash2,
  edit: Edit,
  edit_note: Edit,
  add: Plus,
  content_copy: Copy,
  restart_alt: RefreshCw,
  sync: RefreshCw,
  sort: ArrowUpDown,
  done: CheckCircle,

  // Dark mode
  light_mode: Sun,
  dark_mode: Moon,

  // Trend & Status
  arrow_upward: ArrowUp,
  arrow_downward: ArrowDown,
  trending_up: TrendingUp,
  trending_down: TrendingDown,
  trending_flat: Minus,
  remove: Minus,

  // Alerts & Info
  info: Info,
  warning: AlertTriangle,
  error: AlertCircle,
  error_outline: AlertCircle,
  check_circle: CheckCircle,
  remove_circle_outline: XCircle,
  pending_actions: Clock,
  task_alt: ListChecks,
  priority_high: AlertTriangle,
  arrow_right: ArrowRight,

  // Charts & Analytics
  analytics: BarChart3,
  show_chart: LineChart,
  donut_large: PieChart,
  assessment: BarChart3,
  waterfall_chart: BarChart3,
  leaderboard: BarChart3,
  speed: Gauge,
  table_chart: Table,

  // Finance
  payments: CreditCard,
  account_balance: DollarSign,
  account_balance_wallet: Wallet,
  savings: Wallet,
  sell: DollarSign,
  price_change: DollarSign,
  price_check: DollarSign,
  percent: Percent,
  balance: Scale,

  // Shopping & Commerce
  shopping_cart: ShoppingCart,
  shopping_bag: ShoppingBag,
  store: Store,
  storefront: Store,
  local_shipping: Truck,

  // Inventory & Production
  inventory: Package,
  inventory_2: Boxes,
  category: Layers,
  precision_manufacturing: Factory,
  science: FlaskConical,
  calculate: Hash,
  account_tree: TreeDeciduous,
  compare_arrows: GitCompare,

  // People
  people: Users,
  groups: Users,
  person: User,

  // Weather & Nature
  eco: Leaf,
  content_cut: Droplets,

  // AI & Tech
  auto_awesome: Sparkles,
  psychology: Sparkles,
  lightbulb: Lightbulb,
  smart_toy: Bot,

  // Communication
  email: Mail,
  chat: MessageCircle,
  phone: Phone,
  computer: Monitor,
  print: Printer,

  // Calendar & Time
  calendar_today: Calendar,
  event: CalendarDays,
  event_repeat: Repeat,
  schedule: Clock,
  hourglass_empty: Clock,
  update: RefreshCw,

  // Misc
  verified: ShieldCheck,
  restaurant_menu: UtensilsCrossed,
  refresh: RefreshCw,

  // Cloud
  cloud_off: CloudOff,
  cloud_done: Cloud,
  cloud_sync: Cloud,

  // Status indicators
  star: Star,
  emoji_events: Trophy,
  flag: Flag,
  bolt: Zap,
  swap_horiz: ArrowLeftRight,
  wifi_tethering: Wifi,
  description: FileText,
  health_and_safety: ShieldCheck,
  monitor_heart: Activity,
  tune: SlidersHorizontal,
  diversity_3: Users,
  merge: Merge,
  fiber_new: Sparkles,

  // Settings-specific
  api: Plug,
  dataset: Database,
  badge: IdCard,
  notification_important: BellRing,
  import_export: ArrowDownUp,
};

export type { LucideIcon };
